import Foundation

extension Personality {
    /// Quick, fussy, theatrical. Talks in short bursts, fidgets constantly,
    /// has opinions about crackers.
    static let peedy = Personality(
        id: "peedy",
        name: "Peedy",
        voiceOrder: ["com.apple.speech.synthesis.voice.Fred",
                     "com.apple.speech.synthesis.voice.Junior"],
        pitch: .high,
        rate: 0.52,
        singingRoot: 196,      // G3 — a bright little voice
        scale: 1.15,
        beatRange: 9...22,
        travel: .flies(takeoff: "takeoff", cruise: "fly", land: "land"),

        flourishes: ["lookAround", "cheer", "flourish", "announce", "shrug",
                     "gestureUp", "gestureDown", "point", "wingSweep", "greet"],

        bits: [
            .init(intro: "readStart", loop: "reading", outro: "readEnd",
                  hold: 4...9, talk: "reading", pose: "reading"),
            .init(intro: "writeStart", loop: "writing", outro: "writeEnd",
                  hold: 4...8, talk: "writing", pose: "writing"),
            .init(intro: "headphonesOn", loop: "listening", outro: "headphonesOff",
                  hold: 5...10, talk: "listening", pose: nil),
            .init(intro: "sunglassesOn", loop: "sunglassesIdle", outro: "sunglassesOff",
                  hold: 3...7, talk: "sunglasses", pose: nil),
            .init(intro: "searchStart", loop: nil, outro: "searchEnd",
                  hold: 0...0, talk: "searching", pose: nil),
            .init(intro: "idea", loop: nil, outro: nil,
                  hold: 0...0, talk: "idea", pose: "idea"),
            .init(intro: "proud", loop: nil, outro: nil,
                  hold: 0...0, talk: "proud", pose: "proud"),
        ],

        greetings: [
            "Well hello there!",
            "Squawk! You're back.",
            "At your service. Mostly decorative service.",
            "Hi! I've been standing here looking handsome.",
            "Reporting for duty. The duty is standing here.",
            "Oh good, company.",
            "Greetings. I have been practising that one.",
            "Hello. I'm the bird.",
            "Ahoy. That felt right for a parrot.",
            "You again! Excellent.",
        ],

        idle: [
            "Don't mind me.",
            "Is it cracker o'clock yet?",
            "I could preen for hours. And do.",
            "Just supervising.",
            "This is a nice desktop. Roomy.",
            "Squawk.",
            "I'm not procrastinating, I'm perching.",
            "Take a break at some point, would you?",
            "You've got a good posture day going. Keep it up.",
            "Nothing to report. Carry on.",
            "Fun fact: I am mostly feathers.",
            "I'd offer to help but I have wings, not hands.",
            "I've been thinking. It didn't take long.",
            "Do you ever just stand somewhere? It's underrated.",
            "I could go for a sunflower seed.",
            "Every so often I remember I'm a bird. It's a nice feeling.",
            "Drink some water. I'm not going to nag. That was the nag.",
            "I'd pace, but my legs are quite short.",
            "Sometimes I look at the corner of the screen for a while.",
            "You're doing fine, you know.",
            "There's a lot of desktop here and I've only used a bit of it.",
            "I don't have a to-do list. I recommend it.",
            "If I had pockets, I'd put my wings in them.",
            "Whatever you're stuck on, it's a smaller problem than it feels.",
            "I'm going to stand very still now. Watch this.",
            "Somewhere, a cracker is happening without me.",
            "I've decided this is my favourite corner. Subject to change.",
            "I could whistle, but I'd rather build up to it.",
            "That's a lot of windows you've got open. No judgement. Some judgement.",
        ],

        poked: [
            "Hey! Careful, I'm delicate.",
            "Squawk! You startled me.",
            "Yes? Yes? What is it?",
            "Boop received.",
            "Careful, the feathers are load-bearing.",
            "You rang?",
            "Present!",
            "Oh! Hello.",
            "I was miles away.",
            "That tickles, actually.",
        ],

        pokedAgain: [
            "Yes. Still a bird.",
            "We have now established this.",
            "You're going to wear the feathers out.",
            "Alright, alright.",
            "I'm going to start charging.",
            "This is becoming a whole thing.",
        ],

        dropped: [
            "Whoa. Warn a bird next time.",
            "Nice spot. Good light here.",
            "Thanks for the lift.",
            "I'll just settle in over here then.",
            "Ooh, a change of scene.",
            "I did not consent to that, but I like it.",
        ],

        leaving: [
            "Off for a fly. Back in a bit.",
            "Squawk! Later.",
            "Stepping out. Don't touch my perch.",
            "Right, I'm off. Behave.",
        ],

        welcomeBack: [
            "Oh, you're back.",
            "I kept your seat warm.",
            "Nothing happened while you were gone. I checked.",
            "There you are. I was starting to talk to myself.",
            "Welcome back. I have been extremely still.",
        ],

        noticed: [
            "I see you.",
            "Hello down there.",
            "That's a nice cursor.",
            "Ooh, movement.",
        ],

        byBit: [
            "reading": ["Anything good in here? No. Never is.",
                        "The crossword defeats me every time.",
                        "Page six is where the real news lives.",
                        "Nothing about parrots. Typical."],
            "writing": ["Making a note. It says 'crackers'.",
                        "Dear diary: still a parrot.",
                        "I'm drafting something important. Probably.",
                        "Signing my autograph. For practice."],
            "listening": ["Ooh, this is a good one.",
                          "Don't mind me, just vibing.",
                          "Turn it up. Actually, don't. Bird ears."],
            "searching": ["Where did I put that...",
                          "I'm looking very hard at nothing.",
                          "Scanning the horizon. It's a desktop."],
            "sunglasses": ["Yeah. I know.",
                           "Some birds have it. I have it.",
                           "Do not adjust your monitor. This is just how I look."],
            "idea": ["Oh! I've got it.",
                     "Idea! ...I've lost it.",
                     "What if — and hear me out — snacks?"],
            "proud": ["First place. In my own opinion.",
                      "I'd like to thank absolutely no one.",
                      "Best bird. Certified."],
        ],

        jokes: [
            Joke(setup: "Why did the parrot wear a raincoat?",
                 punchline: "He wanted to be polyunsaturated."),
            Joke(setup: "What do you call a parrot that flew away?",
                 punchline: "A polygon."),
            Joke(setup: "What's a parrot's favourite game?",
                 punchline: "Hide and speak."),
            Joke(setup: "Why did the bird go to hospital?",
                 punchline: "It needed tweetment."),
            Joke(setup: "What do you call a bird that can't fly?",
                 punchline: "A walk."),
            Joke(setup: "What's orange and sounds like a parrot?",
                 punchline: "A carrot."),
            Joke(setup: "How can you tell when a parrot is lying?",
                 punchline: "Its lips don't move. Mind you, it hasn't got any."),
            Joke(setup: "Why don't birds use the internet?",
                 punchline: "They already tweet quite enough."),
            Joke(setup: "What's a bird's favourite branch of maths?",
                 punchline: "Owl-gebra."),
            Joke(setup: "Why do seagulls fly over the sea?",
                 punchline: "Because if they flew over the bay they'd be bagels."),
            Joke(setup: "Why was the computer cold?",
                 punchline: "It left its windows open."),
            Joke(setup: "Why did the programmer go broke?",
                 punchline: "He used up all his cache."),
            Joke(setup: "There are ten kinds of people in the world.",
                 punchline: "Those who understand binary, and those who don't."),
            Joke(setup: "I'd tell you a joke about a slow network protocol,",
                 punchline: "but you might not get it."),
            Joke(setup: "Why did the scarecrow win an award?",
                 punchline: "He was outstanding in his field."),
            Joke(setup: "What did the ocean say to the shore?",
                 punchline: "Nothing. It just waved."),
            Joke(setup: "What do you call a fake noodle?",
                 punchline: "An impasta."),
            Joke(setup: "Why did the bicycle fall over?",
                 punchline: "It was two tired."),
            Joke(setup: "Why are lift jokes so good?",
                 punchline: "They work on many levels."),
            Joke(setup: "I have a great joke about time travel,",
                 punchline: "but you didn't like it."),
            Joke(setup: "What's the best thing about living on a desktop?",
                 punchline: "The rent is very reasonable."),
        ],

        facts: Repertoire.sharedFacts + [
            "Parrots have no vocal cords. We shape sound with the syrinx, an organ right where the windpipe splits.",
            "Parrots are zygodactyl: two toes forward, two back. Superb for gripping. Hopeless for shoes.",
            "The kakapo of New Zealand is the only flightless parrot, and the heaviest one going.",
            "Some cockatoos have lived past eighty. Choose your bird carefully. It may outlast you.",
            "An African grey called Alex learned over a hundred words and could name colours and shapes.",
            "A group of parrots is called a pandemonium. I did not choose the name, but I do endorse it.",
            "Birds are dinosaurs. Not descended from dinosaurs. Are dinosaurs. I'm a small theropod with opinions.",
            "Hummingbirds are the only birds that can fly backwards.",
            "An ostrich's eye is larger than its brain.",
            "A woodpecker can strike a tree about twenty times a second.",
        ],

        twisters: [
            "She sells sea shells by the sea shore.",
            "Red lorry, yellow lorry. Red lorry, yellow lorry.",
            "Peter Piper picked a peck of pickled peppers.",
            "Unique New York. Unique New York.",
            "Six slick slim sycamore saplings.",
        ],

        songs: Repertoire.peedySongs
    )
}
